# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6d99457d8535a8a3d520813dfc23086266fa48e5336d012396dab689bc0ce7979c7abb0ef5c23fce47d30d1f02bf3cec32db390f0d7ea0ede303fdd8c9f8621e

test:
  secret_key_base: 34add3029b1a9bdabd3592641b4a8d51df6a81c7af4f41ea9b443bbc7d8a999b1fc8067ebf431757b4f9ed1505d2be096cf24533433da8c3044dc3bb54e90ef1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
