# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0e40a7b5f38f80bbe342af69a2bbd23573b53eb3d1a847f184bf7831e9ceaab4f85272c2eca0631e9a2caa57e0173e813fc383913da4a37ed8267ee35c94343d

test:
  secret_key_base: bd1865f3b98fd74bf3edcfc7640d9893c8ae0939c1108c8aab90b9d64565118da1da06240ed55d227b8f810ff671f7557f557fb84d4b05362518b79136f280a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
