# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4aaddcbf73beea7a4823b0dd24721998b5888593f87020faa65b985c5b4d977351362034552bba03f495dbaa04a8aa09dde726b405c6b60b83a4088da8580d08

test:
  secret_key_base: 99e5a9909721628abb459c7cb6202d72916bd9d2c0716284a8d7413b7ba0ae6099b0ccad38cc7307be849a8e7d59c1f03fedf3be9671babafa904bbc05a82d88

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
